//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waerp_toolpilot.config.SettingsStore {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class CompanySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CompanySettings defaultInstance = ((CompanySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CompanySettings())));
        
        public static CompanySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Musterfirma GmbH Bochum")]
        public string CompanyName {
            get {
                return ((string)(this["CompanyName"]));
            }
            set {
                this["CompanyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MusterFirma")]
        public string CompanyNameShort {
            get {
                return ((string)(this["CompanyNameShort"]));
            }
            set {
                this["CompanyNameShort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("muster@muster.de")]
        public string CompanyMail {
            get {
                return ((string)(this["CompanyMail"]));
            }
            set {
                this["CompanyMail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0234 00000098")]
        public string CompanyPhone {
            get {
                return ((string)(this["CompanyPhone"]));
            }
            set {
                this["CompanyPhone"] = value;
            }
        }
    }
}
