//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waerp_toolpilot.config.SettingsStore {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class LocalDevice : global::System.Configuration.ApplicationSettingsBase {
        
        private static LocalDevice defaultInstance = ((LocalDevice)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LocalDevice())));
        
        public static LocalDevice Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isTouch {
            get {
                return ((bool)(this["isTouch"]));
            }
            set {
                this["isTouch"] = value;
            }
        }
    }
}
