//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waerp_toolpilot.config.SettingsStore {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class pdfDocument : global::System.Configuration.ApplicationSettingsBase {
        
        private static pdfDocument defaultInstance = ((pdfDocument)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new pdfDocument())));
        
        public static pdfDocument Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double printSpaceLeft {
            get {
                return ((double)(this["printSpaceLeft"]));
            }
            set {
                this["printSpaceLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double printSpaceRight {
            get {
                return ((double)(this["printSpaceRight"]));
            }
            set {
                this["printSpaceRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double printSpaceTop {
            get {
                return ((double)(this["printSpaceTop"]));
            }
            set {
                this["printSpaceTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double printSpaceBottom {
            get {
                return ((double)(this["printSpaceBottom"]));
            }
            set {
                this["printSpaceBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\domin\\\\Source\\\\Workspaces\\\\waerp.inventorysystem\\\\waerp-management\\\\as" +
            "sets\\\\images\\\\app\\\\Druckdatei_wærp_Briefpapier.pdf")]
        public string stationeryPath {
            get {
                return ((string)(this["stationeryPath"]));
            }
            set {
                this["stationeryPath"] = value;
            }
        }
    }
}
